[versions]
kotlin = "2.3.10"
th2-plugin = "0.3.14"
jupiter = "5.14.2"
detekt = "1.23.8"
strikt = "0.34.1"

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }
kubernetes-client = { group = "io.fabric8", name = "kubernetes-client", version = "7.5.2" }
http-client = { group = "com.rabbitmq", name = "http-client", version = "5.4.0" }
java-uuid-generator = { group = "com.fasterxml.uuid", name = "java-uuid-generator", version = "5.2.0" }

mockito-core = { group = "org.mockito", name = "mockito-core", version = "5.21.0" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "6.2.3" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter" }

strikt-core = { group = "io.strikt", name = "strikt-core", version.ref = "strikt" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version = "2.0.3" }
awaitility = { group = "org.awaitility", name = "awaitility", version = "4.3.0" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
download = { id = "de.undercouch.download", version = "5.7.0" }

th2-component = { id = "com.exactpro.th2.gradle.component", version.ref = "th2-plugin" }